packages:
  - 'packages/*'

overrides:
  '@ts-rest/core': 3.53.0-rc.1
  '@ts-rest/express': 3.53.0-rc.1
  '@ts-rest/open-api': 3.53.0-rc.1
  '@ts-rest/*>@ts-rest/core': 3.53.0-rc.1

hoistPattern:
  - '@ts-rest/*'
  - 'zod'

dedupePeerDependents: true

allowBuilds:
  '@scarf/scarf': true
  cpu-features: true
  esbuild: true
  lefthook: true
  sharp: true
  ssh2: true
