import path from "path";
import {
  getAdminOnlyCategoryNames,
  getAllCategoryNames,
} from "@shared/domain/readModels/project/Category";
import { fileURLToPath } from "url";

export const PROJECT_NAMES = [
  "CodeCraft",
  "PixelPulse",
  "BitBlast",
  "NanoGames",
  "ElectraPlay",
  "CircuitForge",
  "ByteBash",
  "CodeCanvas",
  "SparkScript",
  "LogicLand",
  "MicroArcade",
  "CodeCraze",
  "GameGenius",
  "PixelPal",
  "Electronica",
  "CodeQuest",
  "CircuitCraft",
  "ByteBeat",
  "NanoNexus",
  "BitBox",
  "CircuitChaos",
  "CodeCrafter",
  "PixelPioneer",
  "LogicLab",
  "ByteBlitz",
  "CodeWave",
  "NanoNet",
  "ElectraForge",
  "GameGrid",
  "LogicLoom",
  "PixelPlaza",
  "CodeCity",
  "NanoArcade",
  "ElectronEra",
  "BitBazaar",
  "LogicLegends",
  "CodeClan",
  "PixelPortal",
  "CircuitCraze",
  "ByteBuster",
  "NanoNovel",
  "ElectraEden",
  "CodeComet",
  "PixelPlayground",
  "LogicLandia",
  "ByteBounce",
  "CircuitCarnival",
  "CodeCove",
  "NanoNest",
  "ElectraEntertain",
  "GameGalaxy",
  "LogicLabyrinth",
  "ByteBlaster",
  "CodeCompass",
  "NanoNation",
  "ElectraEmpire",
  "GameGarden",
  "PixelPeak",
  "CircuitCelestial",
  "CodeCrusade",
  "NanoNebula",
  "ElectraEnclave",
  "GameGizmo",
  "PixelPlanet",
  "LogicLounge",
  "ByteBeacon",
  "CodeCircus",
  "NanoNook",
  "ElectraElysium",
  "GameGlimpse",
  "PixelParadise",
  "CodeCoast",
  "NanoNirvana",
  "ElectraEdifice",
  "GameGen",
  "PixelPandemonium",
  "LogicLagoon",
  "ByteBlaze",
  "CodeCorridor",
  "HackSimulator",
  "CodeCrunch",
  "SecureCraft",
  "CryptoPulse",
  "DataForge",
  "CipherQuest",
  "HackQuest",
  "SecureSphere",
];

export const USERS = [
  "TechTinkerer",
  "CodeCrafter",
  "PixelPilot",
  "LogicLion",
  "ElectronEager",
  "NanoNomad",
  "CircuitCraze",
  "GameGlider",
  "ByteBlast",
  "CyberCraft",
  "DigitalDynamo",
  "CodeCreator",
  "PixelPulse",
  "LogicLuminary",
  "ElectronEcho",
  "NanoNinja",
  "CircuitChampion",
  "GameGazer",
  "ByteBuddy",
  "TechTornado",
  "CodeChampion",
  "PixelProdigy",
  "LogicLabyrinth",
  "ElectronExplorer",
  "NanoNavigator",
  "CircuitCatalyst",
  "GameGuru",
  "ByteBlaze",
  "DigitalDreamer",
  "CodeCommander",
  "PixelPioneer",
  "LogicLegend",
  "ElectronElite",
  "NanoNerd",
  "CircuitCaptain",
  "GameGenius",
  "ByteBolt",
  "CyberCipher",
  "CodeConqueror",
  "PixelPaladin",
  "LogicLore",
  "ElectronEnigma",
  "CircuitConnoisseur",
  "GameGuardian",
  "ByteBandit",
  "TechTinker",
  "CodeCrusader",
  "PixelPirate",
  "ElectronEagle",
  "CircuitSavant",
  "GameGladiator",
  "ByteBlitz",
  "CyberSavvy",
  "CodeCraftsman",
  "PixelPro",
  "LogicLoreMaster",
  "ElectronEmperor",
  "CircuitChamp",
  "GameGizmo",
  "ByteBrawler",
  "TechTrailblazer",
  "CodeCaptain",
  "PixelPathfinder",
  "LogicLionheart",
  "ElectronExpedition",
  "NanoNoble",
  "CircuitCommander",
  "GameGlobetrotter",
  "CyberSherpa",
  "CyberCraftsman",
  "CodeConnoisseur",
];
export const TWENTY_FOUR_HOURS_IN_MS = 24 * 60 * 60 * 1000;
export const SIX_HUNDRED_DAYS_IN_MS = 600 * TWENTY_FOUR_HOURS_IN_MS;
export const CATEGORY_NAMES = getAllCategoryNames().filter(
  (c) => !getAdminOnlyCategoryNames().includes(c)
);
export const ICON_COUNT = 16;
export const ICON_FILENAMES = Array.from(
  { length: ICON_COUNT },
  (_, i) => `icon${i}.png`
);
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
export const ICONS_ASSETS_PATH = path.resolve(__dirname, "./dummy-icons");
