name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run check:ts
        run: |
          pnpm run check:ts
      - name: Run lint
        run: |
          pnpm run lint
      - name: Run build
        run: |
          pnpm run build
      - name: Start environment
        run: |
          cp packages/backend/.env.test packages/backend/.env
          pnpm --filter badgehub-api run test-db:up
      - name: Populate the DB with test data
        run: |
          pnpm --filter badgehub-api run repopulate-db
      - name: Run test
        run: |
          pnpm run test --coverage
      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: packages/backend
